// Every list file, for the server code (the TV service, the sitemap). A Worker cannot read the
// disk, so each list is imported here; a new list needs its line (npm test checks).
import { collectLists } from '../src/services/lists.js';
import l0 from '../src/lists/after-hours.json' with { type: 'json' };
import l1 from '../src/lists/atomic-age.json' with { type: 'json' };
import l2 from '../src/lists/before-the-code.json' with { type: 'json' };
import l3 from '../src/lists/buster-keaton-in-an-evening.json' with { type: 'json' };
import l4 from '../src/lists/cassette-futures.json' with { type: 'json' };
import l5 from '../src/lists/chaplin-two-reelers.json' with { type: 'json' };
import l6 from '../src/lists/creature-features.json' with { type: 'json' };
import l7 from '../src/lists/crime-and-punishment.json' with { type: 'json' };
import l8 from '../src/lists/cult-80s.json' with { type: 'json' };
import l9 from '../src/lists/drive-in-double-features.json' with { type: 'json' };
import l10 from '../src/lists/eighties-action-mixtape.json' with { type: 'json' };
import l11 from '../src/lists/eighties-action-straight-to-video.json' with { type: 'json' };
import l12 from '../src/lists/eighties-horror-nobody-renewed.json' with { type: 'json' };
import l13 from '../src/lists/epics-and-history.json' with { type: 'json' };
import l14 from '../src/lists/family-matinee.json' with { type: 'json' };
import l15 from '../src/lists/fists-swords-and-tanks.json' with { type: 'json' };
import l16 from '../src/lists/full-throttle.json' with { type: 'json' };
import l17 from '../src/lists/golden-age.json' with { type: 'json' };
import l18 from '../src/lists/gothic-sixties.json' with { type: 'json' };
import l19 from '../src/lists/hidden-gems.json' with { type: 'json' };
import l20 from '../src/lists/hitchcock-before-hollywood-and-after.json' with { type: 'json' };
import l21 from '../src/lists/horror-all-night.json' with { type: 'json' };
import l22 from '../src/lists/kung-fu-theater.json' with { type: 'json' };
import l23 from '../src/lists/late-fees.json' with { type: 'json' };
import l24 from '../src/lists/love-in-black-and-white.json' with { type: 'json' };
import l25 from '../src/lists/monster-matinee.json' with { type: 'json' };
import l26 from '../src/lists/mystery-hour.json' with { type: 'json' };
import l27 from '../src/lists/nineties-after-dark.json' with { type: 'json' };
import l28 from '../src/lists/noir-after-dark.json' with { type: 'json' };
import l29 from '../src/lists/noir-you-can-finish-tonight.json' with { type: 'json' };
import l30 from '../src/lists/once-upon-a-time.json' with { type: 'json' };
import l31 from '../src/lists/orphan-drive-in.json' with { type: 'json' };
import l32 from '../src/lists/orphan-noir.json' with { type: 'json' };
import l33 from '../src/lists/rental-comedy.json' with { type: 'json' };
import l34 from '../src/lists/saturday-matinee-westerns.json' with { type: 'json' };
import l35 from '../src/lists/seventies-heat.json' with { type: 'json' };
import l36 from '../src/lists/seventies-horror.json' with { type: 'json' };
import l37 from '../src/lists/silent-but-not-quiet.json' with { type: 'json' };
import l38 from '../src/lists/song-and-dance.json' with { type: 'json' };
import l39 from '../src/lists/space-and-after.json' with { type: 'json' };
import l40 from '../src/lists/spaghetti-westerns.json' with { type: 'json' };
import l41 from '../src/lists/spies-and-capers.json' with { type: 'json' };
import l42 from '../src/lists/sunday-serials.json' with { type: 'json' };
import l43 from '../src/lists/swords-and-sandals.json' with { type: 'json' };
import l44 from '../src/lists/swords-and-sorcery.json' with { type: 'json' };
import l45 from '../src/lists/the-back-forty.json' with { type: 'json' };
import l46 from '../src/lists/the-comedy-channel.json' with { type: 'json' };
import l47 from '../src/lists/the-drama-department.json' with { type: 'json' };
import l48 from '../src/lists/the-forties.json' with { type: 'json' };
import l49 from '../src/lists/the-projection-booth.json' with { type: 'json' };
import l50 from '../src/lists/the-thirties.json' with { type: 'json' };
import l51 from '../src/lists/the-war-room.json' with { type: 'json' };
import l52 from '../src/lists/the-way-of-the-sword.json' with { type: 'json' };
import l53 from '../src/lists/thrills-and-spills.json' with { type: 'json' };
import l54 from '../src/lists/universal-years.json' with { type: 'json' };
import l55 from '../src/lists/war-stories.json' with { type: 'json' };
import l56 from '../src/lists/where-horror-started.json' with { type: 'json' };

export const LIST_FILES = [l0, l1, l2, l3, l4, l5, l6, l7, l8, l9, l10, l11, l12, l13, l14, l15, l16, l17, l18, l19, l20, l21, l22, l23, l24, l25, l26, l27, l28, l29, l30, l31, l32, l33, l34, l35, l36, l37, l38, l39, l40, l41, l42, l43, l44, l45, l46, l47, l48, l49, l50, l51, l52, l53, l54, l55, l56];
export const LISTS = collectLists(LIST_FILES);
